'use client';
import { useQuery } from '@tanstack/react-query';
import { History, Plus, Minus, ArrowRight, MessageCircle, CheckCircle2, Trash2 } from 'lucide-react'; interface ChangelogEntry { id: string; field_name: string; old_value: string | null; new_value: string | null; change_type: string; user_name: string | null; created_at: string;
} interface TaskChangelogProps { taskId: string;
} const changeTypeConfig: Record<string, { icon: any; color: string; label: string }> = { create: { icon: Plus, color: 'text-emerald-500', label: 'Creado' }, update: { icon: ArrowRight, color: 'text-blue-500', label: 'Actualizado' }, delete: { icon: Trash2, color: 'text-red-500', label: 'Eliminado' }, comment: { icon: MessageCircle, color: 'text-blue-600', label: 'Comentario' }, status: { icon: CheckCircle2, color: 'text-primary', label: 'Estado' },
}; const fieldLabels: Record<string, string> = { name: 'Nombre', description: 'Descripcion', status: 'Estado', priority: 'Prioridad', assignee_id: 'Asignado', start_date: 'Fecha Inicio', due_date: 'Fecha Fin', estimated_hours: 'Horas Estimadas', progress: 'Progreso', parent_id: 'Tarea Padre',
}; function timeAgo(dateStr: string): string { const date = new Date(dateStr); const now = new Date(); const seconds = Math.floor((now.getTime() - date.getTime()) / 1000); if (seconds < 60) return 'hace un momento'; if (seconds < 3600) return `hace ${Math.floor(seconds / 60)}m`; if (seconds < 86400) return `hace ${Math.floor(seconds / 3600)}h`; if (seconds < 604800) return `hace ${Math.floor(seconds / 86400)}d`; return date.toLocaleDateString('es-CL');
} export default function TaskChangelog({ taskId }: TaskChangelogProps) {
  const { data, isLoading } = useQuery({
    queryKey: ['task-changelog', taskId],
    queryFn: async () => {
      const companyId = localStorage.getItem('company_id');
      const res = await fetch(`/api/companies/${companyId}/projects/tasks/${taskId}/changelog?limit=50`);
      if (!res.ok) throw new Error('No se pudo cargar el historial');
      return res.json();
    },
  });
  const entries: ChangelogEntry[] = data?.data?.items || [];
  const total: number = data?.data?.total || 0; if (isLoading) return null; return ( <div className="space-y-3"> <div className="flex items-center gap-2"> <History className="w-3.5 h-3.5 text-muted-foreground" /> <span className="text-[9px] font-semibold text-muted-foreground uppercase tracking-wider"> Historial {total > 0 && `(${total} cambios)`} </span> </div> {entries.length === 0 ? ( <p className="text-xs text-muted-foreground text-center py-3">Sin cambios registrados</p> ) : ( <div className="space-y-2"> {entries.map(entry => { const config = changeTypeConfig[entry.change_type] || changeTypeConfig.update; const Icon = config.icon; const label = fieldLabels[entry.field_name] || entry.field_name; return ( <div key={entry.id} className="flex items-start gap-2 group"> <div className={`mt-0.5 ${config.color}`}> <Icon className="w-3.5 h-3.5" /> </div> <div className="flex-1 min-w-0"> <p className="text-xs text-foreground"> <span className="font-medium">{entry.user_name || 'Sistema'}</span> {' '} {entry.change_type === 'create' && ( <>creo la tarea</> )} {entry.change_type === 'delete' && ( <>elimino la tarea</> )} {entry.change_type === 'comment' && ( <>agrego un comentario</> )} {entry.change_type === 'status' && ( <>cambio estado de <span className="font-medium text-muted-foreground">{entry.old_value}</span> a <span className="font-medium text-primary">{entry.new_value}</span></> )} {entry.change_type === 'update' && ( <> cambio <span className="font-medium">{label}</span> {entry.old_value && entry.old_value !== 'null' && ( <span className="text-muted-foreground"> de <span className="line-through">{entry.old_value}</span></span> )} {entry.new_value && ( <span> a <span className="text-primary font-medium">{entry.new_value}</span></span> )} </> )} </p> <p className="text-[10px] text-muted-foreground">{timeAgo(entry.created_at)}</p> </div> </div> ); })} </div> )} </div> );
}
