import { query } from '@/api/lib/db';
import { getCompanyId, successResponse, errorResponse } from '@/api/lib/helpers';
import { NextRequest } from 'next/server'; export async function GET( request: NextRequest, { params }: { params: { id: string; requestId: string } }
) { try { const companyId = await getCompanyId(request); if (!companyId) return errorResponse('Company ID not found', 400); const { rows } = await query( `SELECT vr.*, e.first_name, e.last_name, e.rut, e.position, e.department FROM vacation_requests vr JOIN employees e ON e.id = vr.employee_id WHERE vr.id = $1 AND vr.company_id = $2`, [params.requestId, companyId] ); if (!rows[0]) return errorResponse('Solicitud no encontrada', 404); return successResponse(rows[0]); } catch { return errorResponse('Failed to fetch request', 500); }
} export async function PUT( request: NextRequest, { params }: { params: { id: string; requestId: string } }
) { try { const companyId = await getCompanyId(request); if (!companyId) return errorResponse('Company ID not found', 400); const body = await request.json(); const { status, rejection_reason } = body; if (!status || !['approved', 'rejected', 'cancelled'].includes(status)) { return errorResponse('Invalid status. Must be: approved, rejected, or cancelled', 400); } // Get the request const { rows: existing } = await query( `SELECT * FROM vacation_requests WHERE id = $1 AND company_id = $2`, [params.requestId, companyId] ); if (!existing[0]) return errorResponse('Solicitud no encontrada', 404); const req = existing[0]; if (req.status !== 'pending') { return errorResponse('Solo se pueden procesar solicitudes pendientes', 400); } // Update request status const { rows } = await query( `UPDATE vacation_requests SET status = $1, rejection_reason = $2, approved_at = NOW(), updated_at = NOW() WHERE id = $3 AND company_id = $4 RETURNING *`, [status, rejection_reason || null, params.requestId, companyId] ); // Get the year from start_date const year = new Date(req.start_date).getFullYear(); const days = parseFloat(req.days); if (status === 'approved') { // Move from pending to used await query( `UPDATE vacation_balances SET days_pending = days_pending - $1, days_used = days_used + $1, updated_at = NOW() WHERE company_id = $2 AND employee_id = $3 AND year = $4`, [days, companyId, req.employee_id, year] ); } else if (status === 'rejected' || status === 'cancelled') { // Return to available await query( `UPDATE vacation_balances SET days_pending = days_pending - $1, days_available = days_available + $1, updated_at = NOW() WHERE company_id = $2 AND employee_id = $3 AND year = $4`, [days, companyId, req.employee_id, year] ); } return successResponse(rows[0]); } catch (e: any) { return errorResponse(e?.message || 'Internal server error', 500); }
} export async function DELETE( request: NextRequest, { params }: { params: { id: string; requestId: string } }
) { try { const companyId = await getCompanyId(request); if (!companyId) return errorResponse('Company ID not found', 400); const { rows: existing } = await query( `SELECT * FROM vacation_requests WHERE id = $1 AND company_id = $2`, [params.requestId, companyId] ); if (!existing[0]) return errorResponse('Solicitud no encontrada', 404); const req = existing[0]; const year = new Date(req.start_date).getFullYear(); const days = parseFloat(req.days); // Return pending days to available if (req.status === 'pending') { await query( `UPDATE vacation_balances SET days_pending = days_pending - $1, days_available = days_available + $1, updated_at = NOW() WHERE company_id = $2 AND employee_id = $3 AND year = $4`, [days, companyId, req.employee_id, year] ); } await query( `DELETE FROM vacation_requests WHERE id = $1 AND company_id = $2`, [params.requestId, companyId] ); return successResponse({ message: 'Solicitud eliminada' }); } catch { return errorResponse('Failed to delete request', 500); }
}
