import { query } from '@/api/lib/db';
import { getCompanyId, successResponse, errorResponse } from '@/api/lib/helpers';
import { NextRequest } from 'next/server'; export async function GET( request: NextRequest, { params }: { params: { id: string; inspectionId: string } }
) { try { const companyId = await getCompanyId(request); if (!companyId) return errorResponse('Company ID not found', 400); const result = await query( `SELECT qi.*, json_build_object('id', w.id, 'name', w.name, 'code', w.code) as warehouse, json_build_object('id', i.id, 'name', i.name) as inspector, json_build_object('id', qc.id, 'name', qc.name) as checklist, json_build_object('id', po.id, 'order_number', po.order_number) as purchase_order, json_build_object('id', s.id, 'name', s.name) as supplier, (SELECT json_agg(json_build_object( 'id', qii.id, 'checklist_item_id', qii.checklist_item_id, 'product_id', qii.product_id, 'product_name', p.name, 'product_sku', p.sku, 'result', qii.result, 'measured_value', qii.measured_value, 'notes', qii.notes, 'check_type', qci.check_type, 'description', qci.description, 'acceptance_criteria', qci.acceptance_criteria, 'min_value', qci.min_value, 'max_value', qci.max_value, 'uom', qci.uom, 'is_critical', qci.is_critical ) ORDER BY qci.sequence) FROM quality_inspection_items qii LEFT JOIN quality_checklist_items qci ON qii.checklist_item_id = qci.id LEFT JOIN products p ON qii.product_id = p.id WHERE qii.inspection_id = qi.id) as items FROM quality_inspections qi LEFT JOIN warehouses w ON qi.warehouse_id = w.id LEFT JOIN profiles i ON qi.inspector_id = i.id LEFT JOIN quality_checklists qc ON qi.checklist_id = qc.id LEFT JOIN purchase_orders po ON qi.purchase_order_id = po.id LEFT JOIN suppliers s ON qi.supplier_id = s.id WHERE qi.id = $1 AND qi.company_id = $2`, [params.inspectionId, companyId] ); if (result.rows.length === 0) return errorResponse('Inspection not found', 404); return successResponse(result.rows[0]); } catch (err) { console.error('Get qualconst validStatuses = ['pending', 'in_progress', 'completed', 'approved', 'rejected']; 
ity inspection error:', err); return errorResponse('Internal server error', 500); }
} export async function PUT( request: NextRequest, { params }: { params: { id: string; inspectionId: string } }
) { try { const companyId = await getCompanyId(request); if (!companyId) return errorResponse('Company ID not found', 400); const body = await request.json(); const { status, inspector_id, notes, started_at, completed_at } = body; if (status && !validStatuses.includes(status)) { return errorResponse(`status must be one of: ${validStatuses.join(', ')}`, 400); } const result = await query( `UPDATE quality_inspections SET status = COALESCE($1, status), inspector_id = COALESCE($2, inspector_id), notes = COALESCE($3, notes), started_at = COALESCE($4, started_at), completed_at = COALESCE($5, completed_at), updated_at = NOW() WHERE id = $6 AND company_id = $7 RETURNING *`, [status, inspector_id, notes, started_at, completed_at, params.inspectionId, companyId] ); if (result.rows.length === 0) return errorResponse('Inspection not found', 404); return successResponse(result.rows[0]); } catch (err) { console.error('Update quality inspection error:', err); return errorResponse('Internal server error', 500); }
} export async function DELETE( request: NextRequest, { params }: { params: { id: string; inspectionId: string } }
) { try { const companyId = await getCompanyId(request); if (!companyId) return errorResponse('Company ID not found', 400); const result = await query( 'DELETE FROM quality_inspections WHERE id = $1 AND company_id = $2 RETURNING id', [params.inspectionId, companyId] ); if (result.rows.length === 0) return errorResponse('Inspection not found', 404); return successResponse({ message: 'Inspection deleted successfully' }); } catch (err) { console.error('Delete quality inspection error:', err); return errorResponse('Internal server error', 500); }
}