import {
  LayoutDashboard,
  Package,
  Warehouse,
  ShoppingCart,
  ShoppingBag,
  Users,
  Truck,
  Handshake,
  Wallet,
  Calculator,
  FolderKanban,
  Monitor,
  CreditCard,
  ScrollText,
  AlertTriangle,
  LucideIcon,
  FileText,
  Plus,
  Receipt,
  BarChart3,
  MapPin,
  DollarSign,
  TrendingUp,
  Tag,
  BookOpen,
  UserCheck,
  Shield,
  Bell,
  Webhook,
  Globe,
  ArrowLeftRight,
  Boxes,
  Wrench,
  History,
  ClipboardList,
  FileBarChart,
  CircleDollarSign,
  Building2,
  UsersRound,
  ClipboardCheck,
  GraduationCap,
  UserPlus,
  Upload,
  Clock,
  List,
  Lock,
  FlaskConical,
  Play,
  Building,
  UtensilsCrossed,
  RefreshCw,
  FileDown,
  Home,
  Building as BuildingIcon,
  Factory,
  CreditCard as CreditCardIcon,
  BookCheck,
  FileSpreadsheet,
  RotateCcw,
  Layers,
  Network,
  Settings as SettingsIcon,
  Key,
  Search,
  Archive,
  Scale,
  Clipboard,
  Star,
  Mail,
  Target,
  Megaphone,
  Calendar,
  Hash,
} from "lucide-react";

export const ICON_MAP = {
  LayoutDashboard,
  Package,
  Warehouse,
  ShoppingCart,
  ShoppingBag,
  Users,
  Truck,
  Handshake,
  Wallet,
  Calculator,
  FolderKanban,
  Monitor,
  CreditCard,
  ScrollText,
  AlertTriangle,
  FileText,
  Plus,
  Receipt,
  BarChart3,
  MapPin,
  DollarSign,
  TrendingUp,
  Tag,
  BookOpen,
  UserCheck,
  Shield,
  Bell,
  Webhook,
  Globe,
  ArrowLeftRight,
  Boxes,
  Wrench,
  History,
  ClipboardList,
  FileBarChart,
  CircleDollarSign,
  Building2,
  UsersRound,
  ClipboardCheck,
  GraduationCap,
  UserPlus,
  Upload,
  Clock,
  List,
  Lock,
  FlaskConical,
  Play,
  Building,
  UtensilsCrossed,
  RefreshCw,
  FileDown,
  Home,
  BuildingIcon,
  Factory,
  CreditCardIcon,
  BookCheck,
  FileSpreadsheet,
  RotateCcw,
  Layers,
  Network,
  SettingsIcon,
  Key,
  Search,
  Archive,
  Scale,
  Clipboard,
  Star,
  Mail,
  Target,
  Megaphone,
  Calendar,
  Hash,
} as const;

export const resolveIcon = (iconName: keyof typeof ICON_MAP | undefined): LucideIcon => {
  if (!iconName) return AlertTriangle;
  return ICON_MAP[iconName] || AlertTriangle;
};

export interface NavSubItem {
  title: string;
  path: string;
  icon?: keyof typeof ICON_MAP;
  subItems?: NavSubItem[];
  comingSoon?: boolean;
  requiredPermission?: { module: string; action: string };
}

export interface NavMainItem {
  title: string;
  path: string;
  icon?: keyof typeof ICON_MAP;
  subItems?: NavSubItem[];
  comingSoon?: boolean;
  requiredPermission?: { module: string; action: string };
}

export interface NavGroup {
  id: number;
  label?: string;
  items: NavMainItem[];
  requiredModule?: string;
}

export const sidebarItems: NavGroup[] = [
  {
    id: 1,
    label: "Principal",
    items: [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: "LayoutDashboard",
      },
      {
        title: "Búsqueda Global",
        path: "/dashboard/search",
        icon: "Search",
      },
      {
        title: "Favoritos",
        path: "/dashboard/favorites",
        icon: "Star",
      },
    ],
  },
  {
    id: 2,
    label: "Ventas",
    requiredModule: "erp",
    items: [
      {
        title: "Clientes",
        path: "/dashboard/customers",
        icon: "Users",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Listado de Clientes", path: "/dashboard/customers", icon: "Users", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Nuevo Cliente", path: "/dashboard/customers/new", icon: "UserPlus", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Segmentación", path: "/dashboard/customers/segments", icon: "Layers", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Historial de Precios", path: "/dashboard/customers/price-history", icon: "History", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "Cotizaciones",
        path: "/dashboard/sales/quotations",
        icon: "FileText",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/sales/quotations", icon: "FileText", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Nueva Cotización", path: "/dashboard/sales/quotations/new", icon: "Plus", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Enviar por Email", path: "/dashboard/sales/quotations/email", icon: "Mail", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Informes", path: "/dashboard/sales/quotations/reports", icon: "BarChart3", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "Pedidos de Venta",
        path: "/dashboard/sales/pedidos",
        icon: "ClipboardList",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/sales/pedidos", icon: "ClipboardList", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Nuevo Pedido", path: "/dashboard/sales/pedidos/new", icon: "Plus", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Importar", path: "/dashboard/sales/pedidos/import", icon: "Upload", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Estados de Pedido", path: "/dashboard/sales/pedidos/status", icon: "SettingsIcon", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Informes", path: "/dashboard/sales/pedidos/reports", icon: "BarChart3", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "Facturación (DTE)",
        path: "/dashboard/sales/invoices",
        icon: "ShoppingCart",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Emitir Factura/Boleta", path: "/dashboard/sales/invoices/new", icon: "Plus", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Listado de DTE", path: "/dashboard/sales/invoices", icon: "FileText", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Facturación Recurrente", path: "/dashboard/sales/recurring", icon: "RotateCcw", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Notas Crédito/Débito", path: "/dashboard/sales/credit-debit", icon: "FileText", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Factoring AEC", path: "/dashboard/sales/factoring", icon: "Handshake", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Informes de Ventas", path: "/dashboard/sales/sales-reports", icon: "BarChart3", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "Guías de Despacho",
        path: "/dashboard/sales/delivery-guides",
        icon: "Truck",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/sales/delivery-guides", icon: "FileText", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Nueva Guía", path: "/dashboard/sales/delivery-guides/new", icon: "Plus", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Guía DTE 52 SII", path: "/dashboard/sales/guia-52", icon: "Truck", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "Cobranza",
        path: "/dashboard/sales/cobranza",
        icon: "DollarSign",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Cuenta Corriente", path: "/dashboard/sales/cobranza", icon: "Clipboard", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Vencimientos", path: "/dashboard/sales/cobranza/due", icon: "Clock", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Carta de Cobro", path: "/dashboard/sales/cobranza/letters", icon: "FileText", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Conciliación Pagos", path: "/dashboard/sales/cobranza/reconciliation", icon: "ArrowLeftRight", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "E-commerce & POS",
        path: "/dashboard/sales/ecommerce",
        icon: "Globe",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Pedidos Web", path: "/dashboard/sales/ecommerce/orders", icon: "Globe", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Sincronizar Stock", path: "/dashboard/sales/ecommerce/sync", icon: "RotateCcw", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Webpay / Transbank", path: "/dashboard/sales/transbank", icon: "CreditCardIcon", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "POS Presencial", path: "/dashboard/pos", icon: "Monitor", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
      {
        title: "Listas de Precios",
        path: "/dashboard/sales/price-lists",
        icon: "Tag",
        requiredPermission: { module: "sales_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/sales/price-lists", icon: "List", requiredPermission: { module: "sales_orders", action: "read" } },
          { title: "Nueva Lista", path: "/dashboard/sales/price-lists/new", icon: "Plus", requiredPermission: { module: "sales_orders", action: "create" } },
          { title: "Reglas de Precio", path: "/dashboard/sales/price-lists/rules", icon: "SettingsIcon", requiredPermission: { module: "sales_orders", action: "read" } },
        ],
      },
    ],
  },
  {
    id: 3,
    label: "Inventario",
    requiredModule: "erp",
    items: [
      {
        title: "Artículos y Servicios",
        path: "/dashboard/inventory",
        icon: "Package",
        requiredPermission: { module: "inventory", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/inventory", icon: "Package", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Nuevo Artículo", path: "/dashboard/inventory/new", icon: "Plus", requiredPermission: { module: "inventory", action: "create" } },
          { title: "Servicios", path: "/dashboard/inventory?type=service", icon: "Wrench", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Categorías", path: "/dashboard/inventory/categories", icon: "Tag", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Variantes", path: "/dashboard/inventory/variants", icon: "Layers", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Unidades de Medida", path: "/dashboard/inventory/uom", icon: "Scale", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Seriales / IMEI", path: "/dashboard/inventory/serials", icon: "ClipboardList", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Lotes / Vencimiento", path: "/dashboard/inventory/batches", icon: "Archive", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Importar / Exportar", path: "/dashboard/inventory/import", icon: "Upload", requiredPermission: { module: "inventory", action: "create" } },
        ],
      },
      {
        title: "Stock y Bodegas",
        path: "/dashboard/warehouses",
        icon: "Warehouse",
        requiredPermission: { module: "inventory", action: "read" },
        subItems: [
          { title: "Bodegas", path: "/dashboard/warehouses", icon: "Warehouse", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Nueva Bodega", path: "/dashboard/warehouses/new", icon: "Plus", requiredPermission: { module: "inventory", action: "create" } },
          { title: "Stock por Bodega", path: "/dashboard/warehouses/stock", icon: "Search", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Transferencias", path: "/dashboard/transfers", icon: "ArrowLeftRight", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Ajustes de Stock", path: "/dashboard/inventory/adjustments", icon: "Wrench", requiredPermission: { module: "inventory", action: "update" } },
          { title: "Conteos Físicos", path: "/dashboard/inventory/counts", icon: "ClipboardCheck", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Reservas / Pedidos", path: "/dashboard/inventory/reservations", icon: "Clipboard", requiredPermission: { module: "inventory", action: "read" } },
        ],
      },
      {
        title: "Producción",
        path: "/dashboard/production",
        icon: "Factory",
        requiredPermission: { module: "production", action: "read" },
        subItems: [
          { title: "Órdenes de Producción", path: "/dashboard/production/orders", icon: "FlaskConical", requiredPermission: { module: "production", action: "read" } },
          { title: "Recetas / Fórmulas (BOM)", path: "/dashboard/recipes", icon: "FileText", requiredPermission: { module: "production", action: "read" } },
          { title: "Costos de Receta", path: "/dashboard/recipes/costs", icon: "Calculator", requiredPermission: { module: "production", action: "read" } },
          { title: "Consumo de Insumos", path: "/dashboard/production/consumption", icon: "Package", requiredPermission: { module: "production", action: "read" } },
        ],
      },
      {
        title: "Informes de Inventario",
        path: "/dashboard/inventory/reports",
        icon: "BarChart3",
        requiredPermission: { module: "inventory", action: "read" },
        subItems: [
          { title: "Stock Actual", path: "/dashboard/inventory/stock-report", icon: "FileBarChart", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Valorización", path: "/dashboard/inventory/valuation", icon: "CircleDollarSign", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Stock Mínimo / Crítico", path: "/dashboard/inventory/low-stock", icon: "AlertTriangle", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Stock Muerto / Sin Movimiento", path: "/dashboard/inventory/dead-stock", icon: "Archive", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Rotación (ABC/XYZ)", path: "/dashboard/inventory/abc-analysis", icon: "BarChart3", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Pronóstico de Demanda", path: "/dashboard/inventory/forecasting", icon: "TrendingUp", requiredPermission: { module: "inventory", action: "read" } },
        ],
      },
      {
        title: "Cierres y Correcciones",
        path: "/dashboard/inventory/closings",
        icon: "Lock",
        requiredPermission: { module: "inventory", action: "read" },
        subItems: [
          { title: "Cierre Mensual", path: "/dashboard/inventory/closings", icon: "Lock", requiredPermission: { module: "inventory", action: "update" } },
          { title: "Corrección Monetaria", path: "/dashboard/inventory/monetary-correction", icon: "CircleDollarSign", requiredPermission: { module: "inventory", action: "read" } },
          { title: "Revalorización", path: "/dashboard/inventory/revaluation", icon: "TrendingUp", requiredPermission: { module: "inventory", action: "update" } },
        ],
      },
    ],
  },
  {
    id: 4,
    label: "Compras",
    requiredModule: "erp",
    items: [
      {
        title: "Órdenes de Compra",
        path: "/dashboard/purchases",
        icon: "ShoppingBag",
        requiredPermission: { module: "purchase_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/purchases", icon: "ShoppingBag", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Nueva OC", path: "/dashboard/purchases/new", icon: "Plus", requiredPermission: { module: "purchase_orders", action: "create" } },
          { title: "Por Aprobar", path: "/dashboard/purchases/pending", icon: "Clock", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Recepción de Mercadería", path: "/dashboard/purchases/receipts", icon: "Boxes", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Devoluciones a Proveedor", path: "/dashboard/purchases/returns", icon: "ArrowLeftRight", requiredPermission: { module: "purchase_orders", action: "read" } },
        ],
      },
      {
        title: "Proveedores",
        path: "/dashboard/suppliers",
        icon: "Truck",
        requiredPermission: { module: "purchase_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/suppliers", icon: "Truck", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Nuevo Proveedor", path: "/dashboard/suppliers/new", icon: "UserPlus", requiredPermission: { module: "purchase_orders", action: "create" } },
          { title: "Portal Proveedores", path: "/dashboard/suppliers/portal", icon: "Globe", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Evaluación / Rating", path: "/dashboard/suppliers/rating", icon: "Star", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Condiciones Comerciales", path: "/dashboard/suppliers/terms", icon: "FileText", requiredPermission: { module: "purchase_orders", action: "read" } },
        ],
      },
      {
        title: "Libro de Compras SII",
        path: "/dashboard/purchases/purchase-book",
        icon: "BookOpen",
        requiredPermission: { module: "purchase_orders", action: "read" },
        subItems: [
          { title: "Libro de Compras", path: "/dashboard/purchases/purchase-book", icon: "BookOpen", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Documentos Recibidos", path: "/dashboard/purchases/documents", icon: "FileDown", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Guías de Despacho", path: "/dashboard/purchases/receipts", icon: "Truck", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Informes Tributarios", path: "/dashboard/purchases/tax-reports", icon: "FileBarChart", requiredPermission: { module: "purchase_orders", action: "read" } },
        ],
      },
      {
        title: "Importaciones",
        path: "/dashboard/purchases/imports",
        icon: "Globe",
        requiredPermission: { module: "purchase_orders", action: "read" },
        subItems: [
          { title: "DIN / DUS", path: "/dashboard/purchases/imports", icon: "Globe", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Costos Aterrizados", path: "/dashboard/purchases/landed-cost", icon: "Truck", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Gastos de Importación", path: "/dashboard/purchases/import-expenses", icon: "DollarSign", requiredPermission: { module: "purchase_orders", action: "read" } },
        ],
      },
      {
        title: "Informes de Compras",
        path: "/dashboard/purchases/reports",
        icon: "BarChart3",
        requiredPermission: { module: "purchase_orders", action: "read" },
        subItems: [
          { title: "Análisis de Proveedores", path: "/dashboard/purchases/reports/suppliers", icon: "BarChart3", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Historial de Precios", path: "/dashboard/purchases/reports/price-history", icon: "History", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Compras por Categoría", path: "/dashboard/purchases/reports/categories", icon: "Tag", requiredPermission: { module: "purchase_orders", action: "read" } },
        ],
      },
    ],
  },
  {
    id: 5,
    label: "Finanzas",
    requiredModule: "erp",
    items: [
      {
        title: "Contabilidad General",
        path: "/dashboard/accounting",
        icon: "Calculator",
        requiredPermission: { module: "accounting", action: "read" },
        subItems: [
          { title: "Plan de Cuentas", path: "/dashboard/accounting", icon: "Calculator", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Asientos Contables", path: "/dashboard/accounting/journal-entries", icon: "FileText", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Nuevo Asiento", path: "/dashboard/accounting/journal-entries/new", icon: "Plus", requiredPermission: { module: "accounting", action: "create" } },
          { title: "Libro Mayor", path: "/dashboard/accounting/general-ledger", icon: "BookOpen", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Balance 8 Columnas", path: "/dashboard/accounting/trial-balance", icon: "FileSpreadsheet", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Estados Financieros (EERR)", path: "/dashboard/accounting/financial-statements", icon: "FileBarChart", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Conciliación Bancaria", path: "/dashboard/accounting/reconciliation", icon: "ArrowLeftRight", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Flujo de Caja", path: "/dashboard/accounting/cashflow", icon: "TrendingUp", requiredPermission: { module: "accounting", action: "read" } },
        ],
      },
      {
        title: "Libros Tributarios SII",
        path: "/dashboard/accounting/sii-books",
        icon: "BookCheck",
        requiredPermission: { module: "accounting", action: "read" },
        subItems: [
          { title: "Libro de Ventas", path: "/dashboard/accounting/sales-book", icon: "BookOpen", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Libro de Compras", path: "/dashboard/purchases/purchase-book", icon: "BookOpen", requiredPermission: { module: "purchase_orders", action: "read" } },
          { title: "Libro de Honorarios", path: "/dashboard/accounting/honorarios", icon: "FileText", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Asistente F29", path: "/dashboard/accounting/f29", icon: "Calculator", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Activo Fijo / Depreciación", path: "/dashboard/accounting/fixed-assets", icon: "Building2", requiredPermission: { module: "accounting", action: "read" } },
        ],
      },
      {
        title: "Cuentas por Cobrar / Pagar",
        path: "/dashboard/finance/ar-ap",
        icon: "DollarSign",
        requiredPermission: { module: "finance", action: "read" },
        subItems: [
          { title: "CxC - Cuenta Corriente Clientes", path: "/dashboard/finance/ar", icon: "Users", requiredPermission: { module: "finance", action: "read" } },
          { title: "CxP - Cuenta Corriente Proveedores", path: "/dashboard/finance/ap", icon: "Truck", requiredPermission: { module: "finance", action: "read" } },
          { title: "Anticipos / Pagos", path: "/dashboard/finance/payments", icon: "CreditCardIcon", requiredPermission: { module: "finance", action: "read" } },
          { title: "Letras / Cheques", path: "/dashboard/finance/checks", icon: "FileText", requiredPermission: { module: "finance", action: "read" } },
        ],
      },
      {
        title: "Centros de Costo",
        path: "/dashboard/cost-centers",
        icon: "CircleDollarSign",
        requiredPermission: { module: "accounting", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/cost-centers", icon: "CircleDollarSign", requiredPermission: { module: "accounting", action: "read" } },
          { title: "Nuevo Centro", path: "/dashboard/cost-centers/new", icon: "Plus", requiredPermission: { module: "accounting", action: "create" } },
          { title: "Distribución de Costos", path: "/dashboard/cost-centers/allocation", icon: "Layers", requiredPermission: { module: "accounting", action: "read" } },
        ],
      },
      {
        title: "Gastos Operacionales",
        path: "/dashboard/expenses",
        icon: "Wallet",
        requiredPermission: { module: "expenses", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/expenses", icon: "Wallet", requiredPermission: { module: "expenses", action: "read" } },
          { title: "Nuevo Gasto", path: "/dashboard/expenses/new", icon: "Plus", requiredPermission: { module: "expenses", action: "create" } },
          { title: "Categorías", path: "/dashboard/expenses/categories", icon: "Tag", requiredPermission: { module: "expenses", action: "read" } },
          { title: "Reportes", path: "/dashboard/expenses/reports", icon: "BarChart3", requiredPermission: { module: "expenses", action: "read" } },
        ],
      },
      {
        title: "Remuneraciones",
        path: "/dashboard/payroll",
        icon: "Wallet",
        requiredPermission: { module: "payroll", action: "read" },
        subItems: [
          { title: "Empleados", path: "/dashboard/payroll?tab=employees", requiredPermission: { module: "payroll", action: "read" } },
          { title: "Períodos de Nómina", path: "/dashboard/payroll?tab=periods", requiredPermission: { module: "payroll", action: "read" } },
          { title: "Vacaciones / Licencias", path: "/dashboard/payroll?tab=vacation", requiredPermission: { module: "payroll", action: "read" } },
          { title: "Previred / DT", path: "/dashboard/payroll/previred", icon: "FileText", requiredPermission: { module: "payroll", action: "read" } },
        ],
      },
    ],
  },
  {
    id: 6,
    label: "CRM y Servicios",
    requiredModule: "erp",
    items: [
      {
        title: "CRM / Oportunidades",
        path: "/dashboard/crm",
        icon: "Handshake",
        requiredPermission: { module: "crm", action: "read" },
        subItems: [
          { title: "Pipeline", path: "/dashboard/crm/pipeline", icon: "Layers", requiredPermission: { module: "crm", action: "read" } },
          { title: "Oportunidades", path: "/dashboard/crm/opportunities", icon: "Target", requiredPermission: { module: "crm", action: "read" } },
          { title: "Actividades / Tareas", path: "/dashboard/crm/activities", icon: "ClipboardCheck", requiredPermission: { module: "crm", action: "read" } },
          { title: "Campañas", path: "/dashboard/crm/campaigns", icon: "Megaphone", requiredPermission: { module: "crm", action: "read" } },
        ],
      },
      {
        title: "Órdenes de Trabajo (Servicios)",
        path: "/dashboard/services/work-orders",
        icon: "Wrench",
        requiredPermission: { module: "work_orders", action: "read" },
        subItems: [
          { title: "Listado", path: "/dashboard/services/work-orders", icon: "Wrench", requiredPermission: { module: "work_orders", action: "read" } },
          { title: "Nueva OT", path: "/dashboard/services/work-orders/new", icon: "Plus", requiredPermission: { module: "work_orders", action: "create" } },
          { title: "Agenda Técnicos", path: "/dashboard/services/schedule", icon: "Calendar", requiredPermission: { module: "work_orders", action: "read" } },
          { title: "Partes de Trabajo", path: "/dashboard/services/reports", icon: "FileText", requiredPermission: { module: "work_orders", action: "read" } },
        ],
      },
      {
        title: "Proyectos",
        path: "/projects",
        icon: "FolderKanban",
        requiredPermission: { module: "projects", action: "read" },
        subItems: [
          { title: "Ver Proyectos", path: "/projects", icon: "FolderKanban", requiredPermission: { module: "projects", action: "read" } },
          { title: "Gantt / Cronograma", path: "/projects/gantt", icon: "LayoutDashboard", requiredPermission: { module: "projects", action: "read" } },
        ],
      },
    ],
  },
  {
    id: 7,
    label: "Reportes y BI",
    requiredModule: "erp",
    items: [
      {
        title: "Dashboard Ejecutivo",
        path: "/dashboard/reports/executive",
        icon: "LayoutDashboard",
        requiredPermission: { module: "reports", action: "read" },
      },
      {
        title: "Reportes de Ventas",
        path: "/dashboard/reports/sales",
        icon: "BarChart3",
        requiredPermission: { module: "reports", action: "read" },
        subItems: [
          { title: "Ventas por Vendedor", path: "/dashboard/reports/sales/by-seller", icon: "UserCheck", requiredPermission: { module: "reports", action: "read" } },
          { title: "Ventas por Producto", path: "/dashboard/reports/sales/by-product", icon: "Package", requiredPermission: { module: "reports", action: "read" } },
          { title: "Ventas por Cliente", path: "/dashboard/reports/sales/by-customer", icon: "Users", requiredPermission: { module: "reports", action: "read" } },
          { title: "Comparativo Períodos", path: "/dashboard/reports/sales/comparison", icon: "TrendingUp", requiredPermission: { module: "reports", action: "read" } },
        ],
      },
      {
        title: "Reportes de Inventario",
        path: "/dashboard/reports/inventory",
        icon: "Package",
        requiredPermission: { module: "reports", action: "read" },
      },
      {
        title: "Reportes Financieros",
        path: "/dashboard/reports/finance",
        icon: "DollarSign",
        requiredPermission: { module: "reports", action: "read" },
        subItems: [
          { title: "Flujo de Caja", path: "/dashboard/reports/finance/cashflow", icon: "TrendingUp", requiredPermission: { module: "reports", action: "read" } },
          { title: "CxC / CxP Aging", path: "/dashboard/reports/finance/aging", icon: "Clock", requiredPermission: { module: "reports", action: "read" } },
          { title: "Rentabilidad por Producto", path: "/dashboard/reports/finance/profitability", icon: "BarChart3", requiredPermission: { module: "reports", action: "read" } },
        ],
      },
      {
        title: "Constructor de Reportes",
        path: "/dashboard/reports/builder",
        icon: "FileBarChart",
        requiredPermission: { module: "reports", action: "read" },
      },
    ],
  },
  {
    id: 8,
    label: "Configuración",
    items: [
      {
        title: "General",
        path: "/dashboard/settings",
        icon: "SettingsIcon",
        requiredPermission: { module: "settings", action: "read" },
        subItems: [
          { title: "Empresa / Datos Tributarios", path: "/dashboard/settings/empresa", icon: "Building2", requiredPermission: { module: "settings", action: "read" } },
          { title: "Sucursales / Bodegas", path: "/dashboard/settings/branches", icon: "Warehouse", requiredPermission: { module: "settings", action: "read" } },
          { title: "Usuarios y Roles", path: "/dashboard/settings/users", icon: "UsersRound", requiredPermission: { module: "settings", action: "read" } },
          { title: "Permisos", path: "/dashboard/settings/permissions", icon: "Key", requiredPermission: { module: "settings", action: "read" } },
          { title: "Series / Folios DTE", path: "/dashboard/settings/series", icon: "Hash", requiredPermission: { module: "settings", action: "read" } },
          { title: "Plantillas de Documentos", path: "/dashboard/settings/templates", icon: "FileText", requiredPermission: { module: "settings", action: "read" } },
          { title: "Correos / Notificaciones", path: "/dashboard/settings/notifications", icon: "Bell", requiredPermission: { module: "settings", action: "read" } },
          { title: "Integraciones / API", path: "/dashboard/settings/integrations", icon: "Network", requiredPermission: { module: "settings", action: "read" } },
          { title: "Webhooks", path: "/dashboard/settings/webhooks", icon: "Webhook", requiredPermission: { module: "settings", action: "read" } },
          { title: "Firma Electrónica (FEA)", path: "/dashboard/settings/fea", icon: "Shield", requiredPermission: { module: "settings", action: "read" } },
          { title: "Centros de Costo", path: "/dashboard/cost-centers", icon: "CircleDollarSign", requiredPermission: { module: "settings", action: "read" } },
          { title: "Monedas / Tasas de Cambio", path: "/dashboard/settings/currencies", icon: "DollarSign", requiredPermission: { module: "settings", action: "read" } },
          { title: "Impuestos / IVA", path: "/dashboard/settings/taxes", icon: "Scale", requiredPermission: { module: "settings", action: "read" } },
        ],
      },
      {
        title: "Auditoría y Logs",
        path: "/dashboard/audit",
        icon: "ScrollText",
        requiredPermission: { module: "audit", action: "read" },
      },
      {
        title: "Alertas y Monitoreo",
        path: "/dashboard/alerts",
        icon: "Bell",
        requiredPermission: { module: "alerts", action: "read" },
      },
    ],
  },
];