export type ModuleType =
  | 'dashboard'
  | 'condominio'
  | 'recetas'
  | 'proyectos'
  | 'hr'
  | 'micuenta'
  | 'ayuda'
  | 'admin'
  | 'restaurante'
  | 'veterinaria'
  | 'gastos'
  | 'auto-talleres';

export interface ModuleSidebarTheme {
  moduleKey: ModuleType;
  title: string;
  badgeLabel: string;
  subtitle: string;
  headerBadgeBg: string;
  headerBadgeText: string;
  headerBadgeBorder: string;
  activeBorderClass: string;
  iconActiveColorClass: string;
  backIconColorClass: string;
  activeSubItemText: string;
  groupActiveText: string;
  activeBadgeClass: string;
  inactiveBadgeClass: string;
  avatarClass: string;
}

export const MODULE_SIDEBAR_THEMES: Record<ModuleType, ModuleSidebarTheme> = {
   dashboard: {
     moduleKey: 'dashboard',
     title: 'ERP Principal',
     badgeLabel: 'ERP',
     subtitle: 'Ventas, Bodega & Finanzas',
     headerBadgeBg: 'bg-brand/10',
     headerBadgeText: 'text-brand-ink',
     headerBadgeBorder: 'border-brand-dark/20',
     activeBorderClass: 'border-brand-dark',
     iconActiveColorClass: 'text-brand-ink',
     backIconColorClass: 'text-brand-ink',
     activeSubItemText: 'text-brand-ink',
     groupActiveText: 'text-brand-ink',
     activeBadgeClass: 'bg-brand text-white border-brand-dark font-black',
     inactiveBadgeClass: 'bg-brand/10 text-ink border-brand-dark/20 font-extrabold',
     avatarClass: 'bg-brand/10 text-brand-ink border-brand-dark/30',
   },
   condominio: {
     moduleKey: 'condominio',
     title: 'Mi Condominio',
     badgeLabel: 'Condominio',
     subtitle: 'Administración Ley 21.442',
     headerBadgeBg: 'bg-sky-accent/30',
     headerBadgeText: 'text-[#006680]',
     headerBadgeBorder: 'border-sky-accent/50',
     activeBorderClass: 'border-sky-accent',
     iconActiveColorClass: 'text-[#006680]',
     backIconColorClass: 'text-[#006680]',
     activeSubItemText: 'text-[#006680]',
     groupActiveText: 'text-[#006680]',
     activeBadgeClass: 'bg-sky-accent text-[#006680] border-sky-accent font-black',
     inactiveBadgeClass: 'bg-sky-accent/30 text-ink border-sky-accent/50 font-extrabold',
     avatarClass: 'bg-sky-accent/30 text-[#006680] border-sky-accent/50',
   },
   recetas: {
     moduleKey: 'recetas',
     title: 'Recetas / BOM',
     badgeLabel: 'Recetas',
     subtitle: 'Producción & Insumos',
     headerBadgeBg: 'bg-peach/30',
     headerBadgeText: 'text-[#c64d00]',
     headerBadgeBorder: 'border-peach/50',
     activeBorderClass: 'border-peach',
     iconActiveColorClass: 'text-[#c64d00]',
     backIconColorClass: 'text-[#c64d00]',
     activeSubItemText: 'text-[#c64d00]',
     groupActiveText: 'text-[#c64d00]',
     activeBadgeClass: 'bg-peach text-[#c64d00] border-peach font-black',
     inactiveBadgeClass: 'bg-peach/30 text-ink border-peach/50 font-extrabold',
     avatarClass: 'bg-peach/30 text-[#c64d00] border-peach/50',
   },
   proyectos: {
     moduleKey: 'proyectos',
     title: 'Proyectos & Obras',
     badgeLabel: 'Proyectos',
     subtitle: 'Presupuestos & Hitos',
     headerBadgeBg: 'bg-cotton-candy/20',
     headerBadgeText: 'text-[#8A6100]',
     headerBadgeBorder: 'border-cotton-candy/40',
     activeBorderClass: 'border-cotton-candy',
     iconActiveColorClass: 'text-[#8A6100]',
     backIconColorClass: 'text-[#8A6100]',
     activeSubItemText: 'text-[#8A6100]',
     groupActiveText: 'text-[#8A6100]',
     activeBadgeClass: 'bg-cotton-candy text-ink border-cotton-candy font-black',
     inactiveBadgeClass: 'bg-cotton-candy/20 text-ink border-cotton-candy/40 font-extrabold',
     avatarClass: 'bg-cotton-candy/20 text-[#8A6100] border-cotton-candy/40',
   },
   hr: {
     moduleKey: 'hr',
     title: 'RRHH & Sueldos',
     badgeLabel: 'RRHH',
     subtitle: 'Liquidaciones & Asistencia',
     headerBadgeBg: 'bg-peony/40',
     headerBadgeText: 'text-[#db2777]',
     headerBadgeBorder: 'border-peony/50',
     activeBorderClass: 'border-peony',
     iconActiveColorClass: 'text-[#db2777]',
     backIconColorClass: 'text-[#db2777]',
     activeSubItemText: 'text-[#db2777]',
     groupActiveText: 'text-[#db2777]',
     activeBadgeClass: 'bg-peony text-[#db2777] border-peony font-black',
     inactiveBadgeClass: 'bg-peony/40 text-ink border-peony/50 font-extrabold',
     avatarClass: 'bg-peony/40 text-[#db2777] border-peony/50',
   },
   micuenta: {
     moduleKey: 'micuenta',
     title: 'Mi Cuenta SaaS',
     badgeLabel: 'Cuenta',
     subtitle: 'Suscripción & Módulos',
     headerBadgeBg: 'bg-lavender/30',
     headerBadgeText: 'text-[#8A6100]',
     headerBadgeBorder: 'border-lavender/50',
     activeBorderClass: 'border-lavendon',
     iconActiveColorClass: 'text-[#8A6100]',
     backIconColorClass: 'text-[#8A6100]',
     activeSubItemText: 'text-[#8A6100]',
     groupActiveText: 'text-[#8A6100]',
     activeBadgeClass: 'bg-lavender text-[#8A6100] border-lavender font-black',
     inactiveBadgeClass: 'bg-lavender/30 text-ink border-lavender/50 font-extrabold',
     avatarClass: 'bg-lavender/30 text-[#8A6100] border-lavender/50',
   },
   ayuda: {
     moduleKey: 'ayuda',
     title: 'Centro Ayuda',
     badgeLabel: 'Soporte',
     subtitle: 'Documentación & Tickets',
     headerBadgeBg: 'bg-mint/30',
     headerBadgeText: 'text-forest',
     headerBadgeBorder: 'border-mint/50',
     activeBorderClass: 'border-mint',
     iconActiveColorClass: 'text-forest',
     backIconColorClass: 'text-forest',
     activeSubItemText: 'text-forest',
     groupActiveText: 'text-forest',
     activeBadgeClass: 'bg-mint text-forest border-mint font-black',
     inactiveBadgeClass: 'bg-mint/30 text-ink border-mint/50 font-extrabold',
     avatarClass: 'bg-mint/30 text-forest border-mint/50',
   },
   admin: {
     moduleKey: 'admin',
     title: 'Super Admin',
     badgeLabel: 'Admin',
     subtitle: 'Consola Global SaaS',
     headerBadgeBg: 'bg-brand/10',
     headerBadgeText: 'text-brand-ink',
     headerBadgeBorder: 'border-brand-dark/20',
     activeBorderClass: 'border-brand-dark',
     iconActiveColorClass: 'text-brand-ink',
     backIconColorClass: 'text-brand-ink',
     activeSubItemText: 'text-brand-ink',
     groupActiveText: 'text-brand-ink',
     activeBadgeClass: 'bg-brand/80 text-white border-brand-dark font-black',
     inactiveBadgeClass: 'bg-brand/10 text-ink border-brand-dark/20 font-extrabold',
     avatarClass: 'bg-brand/10 text-brand-ink border-brand-dark/30',
   },
   restaurante: {
     moduleKey: 'restaurante',
     title: 'Restaurante & POS',
     badgeLabel: 'POS',
     subtitle: 'Mesas, KDS, Carta & QR',
     headerBadgeBg: 'bg-apricot/15',
     headerBadgeText: 'text-[#cc5500]',
     headerBadgeBorder: 'border-apricot/40',
     activeBorderClass: 'border-apricot',
     iconActiveColorClass: 'text-[#cc5500]',
     backIconColorClass: 'text-[#cc5500]',
     activeSubItemText: 'text-[#cc5500]',
     groupActivityText: 'text-[#cc5500]',
     activeBadgeClass: 'bg-apricot text-[#cc5500] border-apricot font-black',
     inactiveBadgeClass: 'bg-apricot/15 text-ink border-apricot/40 font-extrabold',
     avatarClass: 'bg-apricot/15 text-[#cc5500] border-apricot/40',
   },
   veterinaria: {
     moduleKey: 'veterinaria',
     title: 'Veterinaria & Clínica',
     badgeLabel: 'VET',
     subtitle: 'Pacientes, Consultas & Fichas',
     headerBadgeBg: 'bg-mint/30',
     headerBadgeText: 'text-forest',
     headerBadgeBorder: 'border-mint/50',
     activeBorderClass: 'border-mint',
     iconActiveColorClass: 'text-forest',
     backIconColorClass: 'text-forest',
     activeSubItemText: 'text-forest',
     groupActiveText: 'text-forest',
     activeBadgeClass: 'bg-mint text-forest border-mint font-black',
     inactiveBadgeClass: 'bg-mint/30 text-ink border-mint/50 font-extrabold',
     avatarClass: 'bg-mint/30 text-forest border-mint/50',
   },
   gastos: {
     moduleKey: 'gastos',
     title: 'Gestión de Gastos',
     badgeLabel: 'Gastos',
     subtitle: 'Control Operativo & Tributario',
     headerBadgeBg: 'bg-peony/40',
     headerBadgeText: 'text-[#db2777]',
     headerBadgeBorder: 'border-peony/50',
     activeBorderClass: 'border-peony',
     iconActiveColorClass: 'text-[#db2777]',
     backIconColorClass: 'text-[#db2777]',
     activeSubItemText: 'text-[#db2777]',
     groupActiveText: 'text-[#db2777]',
     activeBadgeClass: 'bg-peony text-[#db2777] border-peony font-black',
     inactiveBadgeClass: 'bg-peony/40 text-ink border-peony/50 font-extrabold',
     avatarClass: 'bg-peony/40 text-[#db2777] border-peony/50',
   },
   'auto-talleres': {
     moduleKey: 'auto-talleres',
     title: 'Talleres Automotrices',
     badgeLabel: 'Talleres',
     subtitle: 'Órdenes, Vehículos & Técnicos',
     headerBadgeBg: 'bg-apricot/15',
     headerBadgeText: 'text-[#cc5500]',
     headerBadgeBorder: 'border-apricot/40',
     activeBorderClass: 'border-apricot',
     iconActiveColorClass: 'text-[#cc5500]',
     backIconColorClass: 'text-[#cc5500]',
     activeSubItemText: 'text-[#cc5500]',
     groupActiveText: 'text-[#cc5500]',
     activeBadgeClass: 'bg-apricot text-[#cc5500] border-apricot font-black',
     inactiveBadgeClass: 'bg-apricot/15 text-ink border-apricot/40 font-extrabold',
     avatarClass: 'bg-apricot/15 text-[#cc5500] border-apricot/40',
   },
};